### ISSUE TITLE
Website roadmap for V1

### ISSUE THREAD

**Issue by AffectedArc07** [DMPM-Team/website#1]
Core:
- [x] Add some sort of secrets store
- [x] Add GitHub OAuth sign in (I aint dealing with passwords)
- [ ] Write documentation
- [ ] Have download page give a link to the latest GitHub release as well as install instructions (put it in your path)
- [x] Package upload stuff (See below)
- [x] Database stuff (See below)

Database:
- [x] Table to keep track of GitHub usernames and user IDs (As a cache to avoid mass API queries)
- [x] Table to keep track of packages (ID, name, description, owner, creation_date)
- [x] Table to keep track of package versions (ID, package_id [FK], release notes, version number, download count, release_date, byond version)
- [x] All of this **needs** to be managed by EntityFramework. No exceptions.

Package creation:
- [x] Restrict names to alphanumeric, no spaces, all lowercase
- [x] Short package description
- [x] Package URL stuff (Documentation + Source), both optional
- [x] Redirect to the package page on completion
- [x] Package page need an edit button

Release creation:
- [x] Accept version as semver
- [x] Accept package upload in zip format
- [x] Documentation dictates how a zip must be laid out (There must be a `dmpm_includes.dm` in the top directory with the required DM file includes inside)
- [x] ~~*Maybe* some sort of validation to see if the code compiles. Package should be independent. I could make a test env that grabs the BYOND version the package wants, and compiles `dmpm_includes.dm`~~ Can be done later
- [x] Obviously, make it so you can only upload to packages you own
- [x] Cap uploads to 5mb
- [x] Store packages in the ASP app `app_data`
- [x] `App_Data/Packages/Package_Id/Version_Id.zip` --> GET `/download/packagenames/version`
- [x] Flow will be create package --> create version
- [x] Package data format
- [ ] Validate that the package has an `includes.dm` file inside it (ZipFile.files)
```
package_root:
    |
    |--- includes.dm
    |     |___ in here is your #include statements for stuff in `code`
    |
    |--- code
          |___ in here is your code that changes with each release
```

Pages - Dynamic:
- [x] List all packages with search and paging
- [x] List packages belonging to one user
- [x] List releases and info for a package
- [x] Package creation page (see above)
- [x] Release upload page (see above)

Pages - Static:
- [ ] Install page
- [ ] Client Documentation page
- [ ] Package Documentation page

Package download:
- [x] Get latest version by max ID in the releases table where the package ID corresponds properly. 

Other:
- [ ] CI for the repo
- [ ] Readme for the repo
